-   format: string
    from:
    -   category:   OST_MechanicalEquipment
        parameters:
        - Designation
        - separator(-)
        - Mark
    to:
    -   category:   OST_ElectricalFixtures
        parameters:
        - Mark
        - EquipmentID

-   format: string
    from:
    -   category:   OST_MechanicalEquipment
        parameters:
        - Manufacturer
    to:
    -   category:   OST_ElectricalFixtures
        parameters:
        - Associated Mechanical Unit Model