-   rule: closest
    from:
        category:   Electrical Fixtures
        parameters:
        - Comments
        - separator(-)
        - Mark
    to:
        category:   Lighting Fixtures
        parameters:
        - Comments