# -   block: 2X4LN
#     category: Lighting Fixtures
#     family: Type A
#     type: A4
#     host: Ceiling

# # TYPE A #
# ##########
#
# -   block: 2X4L
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: AX - Existing 4-lamp fixture
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: 2X4L_1
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: AX - Existing 4-lamp fixture
#     host: Reference Plane (01 LEVEL - 9'-0")
#
-   block: 2X4LN
    category: Lighting Fixtures
    family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
    type: AEX - Existing 4-lamp fixture (Emergency)
    host: Ceiling
#
# -   block: 2X4C
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: CX - Existing 2-lamp fixture
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: _U31
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: CEX - Existing 2-lamp fixture (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (-0' 9 111/128", 0' 3 79/128")
#     orientation-offset: -90°
#
# -   block: _U32
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: CEX - Existing 2-lamp fixture (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (0' 10 23/32", 1' 1 15/64")
#     orientation-offset: -90°
#
# -   block: _U51
#     category: Lighting Fixtures
#     family: TYPE A - RECESSED 2x4 LIGHT FIXTURE - LED
#     type: CEX - Existing 2-lamp fixture (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (-1' 1 15/64", -0' 9 115/128")
#     rotate-origin-offset: -90°
#     orientation-offset: -90°
#
# # TYPE D #
# ##########
#
# -   block: 2X2L
#     category: Lighting Fixtures
#     family: TYPE D - RECESSED 2x2 LIGHT FIXTURE - LED
#     type: DX - Existing 2 Lamp Fixture
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: _U36
#     category: Lighting Fixtures
#     family: TYPE D - RECESSED 2x2 LIGHT FIXTURE - LED
#     type: DEX - Existing 2 Lamp Fixture (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (-0' 7 59/64", -0' 10 39/256")
#
# -   block: _U37
#     category: Lighting Fixtures
#     family: TYPE D - RECESSED 2x2 LIGHT FIXTURE - LED
#     type: DEX - Existing 2 Lamp Fixture (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: H_LIT
#     category: Lighting Fixtures
#     family: TYPE D - RECESSED 2x2 LIGHT FIXTURE - LED
#     type: D1X - Existing 1 Lamp Fixture
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (-1' 0", 1' 0")
#     rotate-origin-offset: 0°
#     orientation-offset: -90°
#
# # TYPE F #
# ##########
#
# -   block: F_CH
#     category: Lighting Fixtures
#     family: TYPE F - PENDANT STRIP LIGHT FIXTURE - LED
#     type: FX
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: F_CH_1
#     category: Lighting Fixtures
#     family: TYPE F - PENDANT STRIP LIGHT FIXTURE - LED
#     type: FX
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: F_CH_2
#     category: Lighting Fixtures
#     family: TYPE F - PENDANT STRIP LIGHT FIXTURE - LED
#     type: FX
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# # TYPE J #
# ##########
#
# -   block: EWALLL
#     category: Lighting Fixtures
#     family: TYPE JCX - EXISTING EXTERIOR WALL PACK LIGHT FIXTURE - LED
#     type: Standard
#     host: Wall (2' 0")
#
# -   block: WALLL
#     category: Lighting Fixtures
#     family: TYPE JCX - EXISTING EXTERIOR WALL PACK LIGHT FIXTURE - LED
#     type: Standard
#     host: Wall (2' 0")
#
# # TYPE K #
# ##########
#
# -   block: K_LIT
#     category: Lighting Fixtures
#     family: TYPE K - BUGEYE EMERGENCY LIGHTING FIXTURE
#     type: KX - Existing
#     host: Wall (2' 0")
#
# # TYPE l #
# ##########
#
# -   block: 1X4L
#     category: Lighting Fixtures
#     family: TYPE L - RECESSED 1x4 LIGHT FIXTURE - LED
#     type: LX - Existing 1x4
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: 1X4L_1
#     category: Lighting Fixtures
#     family: TYPE L - RECESSED 1x4 LIGHT FIXTURE - LED
#     type: LX - Existing 1x4
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: _U55
#     category: Lighting Fixtures
#     family: TYPE L - RECESSED 1x4 LIGHT FIXTURE - LED
#     type: LEX - Existing 1x4 (Emergency)
#     host: Reference Plane (01 LEVEL - 9'-0")
#     origin-offset: (0, -0' 7 87/256")
#     parameters:
#     - Emergency Light <True/False> = True
#
# # TYPE P #
# ##########
#
# -   block: DOWNL
#     category: Lighting Fixtures
#     family: TYPE P - RECESSED DOWNLIGHT FIXTURE - LED
#     type: PX - Existing Downlight
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# # TYPE WS #
# ###########
#
# -   block: F_SUR
#     category: Lighting Fixtures
#     family: Type WS - SURFACE MOUNTED WRAP AROUND
#     type: W4X - 4' - Existing
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: F_SUR_1
#     category: Lighting Fixtures
#     family: Type WS - SURFACE MOUNTED WRAP AROUND
#     type: W4X - 4' - Existing
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# -   block: F_SUR_2
#     category: Lighting Fixtures
#     family: Type WS - SURFACE MOUNTED WRAP AROUND
#     type: W2X - 2' - Existing
#     host: Reference Plane (01 LEVEL - 9'-0")
#
# # TYPE X #
# ##########
#
# -   block: LTX1C1
#     category: Lighting Fixtures
#     family: TYPE X - CEILING MTD - UPDATED
#     type: X1C - EXIT SIGN SINGLE SIDED - AC ONLY
#     host: Level
#     parameters:
#     - Fixture Height <Length> = 9' 0"
#
# -   block: LTX2C1
#     category: Lighting Fixtures
#     family: TYPE X - CEILING MTD - UPDATED
#     type: X2C - EXIT SIGN DOUBLE SIDED - AC ONLY
#     host: Level
#     parameters:
#     - Fixture Height <Length> = 9' 0"
# 
# -   block: LTX1W1
#     category: Lighting Fixtures
#     family: TYPE X - WALL MTD - UPDATED
#     type: X1LWX - EXISTING WITH LAMP HEADS
#     host: Wall and Level (4')
#
# -   block: >-
#         *U28
#     category: Lighting Fixtures
#     family: TYPE X - WALL MTD - UPDATED
#     type: X1LWX - EXISTING WITH LAMP HEADS
#     host: Wall and Level (4')
